### ISSUE TITLE
matchingAssocationFieldRequiresObject not triggerd with IN()

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/orm#6263]
So not sure if this is a bug. For me it's actually handy because now i can still filter the Entities.

But when i try to filter on a relation's id with using a Criteria and the EQ expression i get the exception matchingAssocationFieldRequiresObject. But when i filter with a IN expression everything works as expected. Is this by design ?

Additionally, is there any other way to use EQ expression for filtering by relation id

**Comment by oleg-andreyev** [comment]
I've encountered the same behaviors.

Tagging "core" contributors 
@beberlei @SenseException @jwage @lcobucci @guilhermeblanco @greg0ire @Ocramius maybe they have ideas/knowledge why it was done like so initially

**Comment by greg0ire** [comment]
It's hard to understand what this is about: https://github.com/doctrine/orm/search?q=matchingAssocationFieldRequiresObject&unscoped_q=matchingAssocationFieldRequiresObject

I think I won't be able to help anyways, but I think this should come with a stack trace and sample code. And since this is more of a question, please go ask it on Stack Overflow, a place where people get downvoted when they are imprecise :trollface:  Link to the question here, and if you can't get an answer tell me, I will spend some reputation to set a bounty on it.
