### ISSUE TITLE
[Documentation] Extra lazy docs do not mention removeElement eagerness

### ISSUE THREAD

**Issue by malarzm** [doctrine/orm#7765]
TIL that not initialized collection in `EXTRA_LAZY` mode will remove element with `->removeElement()` from the database without waiting for a `flush`. I think it should be mentioned in the docs https://github.com/doctrine/orm/blob/04762015c6b4fe1dc2f3c1043c307710b2c59fa7/lib/Doctrine/ORM/PersistentCollection.php#L355-L365

**Comment by DonCallisto** [comment]
As `$persister` here 

https://github.com/doctrine/orm/blob/04762015c6b4fe1dc2f3c1043c307710b2c59fa7/lib/Doctrine/ORM/PersistentCollection.php#L362

could be of two types `ManyToManyPersister` and `OneToMany` persister this is the relevant code

https://github.com/doctrine/orm/blob/e1bb9e005d2676c42ec19521db9569a28da179d3/lib/Doctrine/ORM/Persisters/Collection/OneToManyPersister.php#L159
https://github.com/doctrine/orm/blob/1ab9d0b1942a6b70d01640d51056a71916255ecf/lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php#L234

I think the docs should point out this situation - where applicable - both in https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#orphan-removal and https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/extra-lazy-associations.html#extra-lazy-associations

BTW the fact that `ManyToManyPersister` does not contemplate `orphanRemoval` makes me wonder if this is a bug or is done by design.

As said in #7852 that's now closed, I'm willing to work on this PR if think is worthy.

**Comment by flaushi** [comment]
If I see this correctly, one viable workaround is - and could well be mentioned in the docs - that if one needs the event listener to be called, one can replace
```
$entity->manyToManyCollection->removeElement($other);
```
with
```
$index = $entity->manyToManyCollection->indexOf($other);
if($index !== false)
    $entity->manyToManyCollection->remove($index);
```

**Comment by DonCallisto** [comment]
The intent of `EXTRA_LAZY` is to prevent the whole collection to be loaded so I don't think it has too much sense in this context.
Moreover how can one change that section of code?
Lastly, this is the intended behaviour.

**Comment by malarzm** [comment]
Closing as behaviour was changed in #7940
