### ISSUE TITLE
On softdelete entity gets updated twice if flushed twice

### ISSUE THREAD

**Issue by TerjeBr** [doctrine/orm#7958]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | latest

#### Summary

This bug was first reported at https://github.com/Atlantic18/DoctrineExtensions/issues/2038
but it seems like it might be the case that it is a doctrine bug instead of a bug with that extension.

#### Current behavior

After a soft-delteable entity is removed, after a flush the attribute `deleted_at` is still recorded in `UoW->originalEntityData` as `null` instead of the current time. If then the code comes to a new flush, that field will be updated to the current time a second time around. This gives an extra roundtrip to the database that should not be necessary.

#### How to reproduce

Make an entity that uses soft delete with the  https://github.com/Atlantic18/DoctrineExtensions

Then in your code with the entity loaded from the database into the variable $entity do:
```
$em->remove($entity);
$em->flush();
$em->flush();
```

Both flush operations will emit "update" statements to the database to soft-delete the entity, and it will be updated twice.

#### Expected behavior

The entity should only be updated in the first flush operation, and nothing should happen in the database on any subsequent flush.

**Comment by beberlei** [comment]
Sorry to disappoint you, but this is not a Doctrine bug, soft delete behavior like this extension provides is very fragile given the UoW complexity.

I wish extensions would implement soft delete by throwing an exception when passing an entity to remove that should not be deleted and instructing the developer to "set" the deletedAt timestamp and then flushing.

**Comment by TerjeBr** [comment]
The whole point of the extension is to change the behaviour of `$em->remove()` to soft-delete on flush, instead of doing a hard delete. Then it will be enough to just change the configuration of the entity, and you do not need to go through all your code base to change all the hard deletes to soft deletes. Does that  make sense to you?

**Comment by doctorby** [comment]
@beberlei 
Extension just use `scheduleExtraUpdate` of UoW, but `UoW->originalEntityData` not updated with new data. 
As result, we have updated entity, and outdated `UoW->originalEntityData` and second flush recalc changeset and tries to sync db with redundant update query.

should `originalEntityData` be updated with data from `scheduleExtraUpdate` since object&db successfully updated?

**Comment by beberlei** [comment]
@doctorby if you find a way to manipulate originalEntityData in a way to avoid the second flush, yes that should be the way to go. Messing with the UoW means that you bear the sole responsibility of keeping it in a state that it understands.

@TerjeBr I don't know what to say, the extension changes the behavior in a way that we did not intend it to be used. Extensions that modify the UnitOfWork are responsible to make it so that the UnitOfWork doesn't get confused. Other extensions like SimpleThings/entity-audit for example create a second history table and copy the state over when it gets deleted. That is a much less invasive approach.
