### ISSUE TITLE
findBy() doesn't work with Single Table Inheritance (SINGLE_TABLE) child object.

### ISSUE THREAD

**Issue by JakubSzczesniak** [doctrine/orm#7962]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.1

#### Summary

In Single Table Inheritance (SINGLE_TABLE) is impossible to filter by parameters included in child objects.

#### Current behavior

```
In ORMException.php line 101:

  Unrecognized field: deliveredAt
```

#### How to reproduce

Create abstract entity fe `AbstractOrder`
Create child entity fe `ShippingOrder` with any parameter (for me is deliveredAt).
Try to get filtered objects by `findBy()` with child parameter. 

P.S. My orderRepository has `AbstractOrder` in `entityClass` parameter.

#### Expected behavior

Select objects with filters.

**Comment by holtkamp** [comment]
If I remember correctly this is expected behavior. Your `OrderRepository` is only aware of the properties of the `AbstractOrder` Entity so no filtering can be done on properties of the child `ShippingOrder`. 

You probably need to create a dedicated `ShippingOrderRepository` for the `ShippingOrder` Entity to be able to filter on the `ShippingOrder.deliveredAt` property...

**Comment by SenseException** [comment]
This error seems to be valid in case you try the following:

```php
$entityManager->getRepository(AbstractOrder::class)->findBy(['deliveredAt' => $datetime]);
```

The `AbstractOrder` doesn't know about the existance of `deliveredAt` despite the base table of your single inheritance structure has a `delivered_at` column. Only a repository for `ShippingOrder` is aware of this field, because it is defined in the `ShippingOrder` entity.
