### ISSUE TITLE
Support primary key as part of another entity's primary key?

### ISSUE THREAD

**Issue by drupol** [doctrine/orm#8359]
Hello there,

I've been bugging some core members lately about an issue with Doctrine. It turns out that what I was trying to do is not feasible in Doctrine as of today.
This 10 years old [commit](https://github.com/doctrine/orm/commit/2d27a99a0bdea2bea3379a213fdbfc11e784234a) prevent the use primary key as part of antother entity's primary key.

Here's the PR where you can follow what I was trying to do: https://github.com/drupol/composite/pull/5

That project is just a very basic project that anyone can clone an experiment with to highlight the issue.

I also created a PR and simplified my small proof-of-concept project in order to show the issue with only 2 entities: https://github.com/drupol/composite/pull/6 (branch: `doctrine-limitation-hit`).

My question are:

1.  How much work would it be to add support for mapping entity with a composite primary key as part of a primary key of another entity?
2. Can we quantify what we would have to do?
3. Where to start?

Thanks!

**Comment by greg0ire** [comment]
Link to the guard clause that prevents this: https://github.com/doctrine/orm/blob/404edd418b983d14a35c62ab297a4ead66ed2063/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L1514-L1519

**Comment by greg0ire** [comment]
3. I'd say start by understanding why the guard clause above was added. Try removing it, and see what breaks.

**Comment by beberlei** [comment]
Yes, this guard clause was added, because I believe much more internal changes are necessary to make this case work. 

First I believe the main problem was entity identifier hashes, i.e. the key thats being generated for these entities to be stored in the identityMap. It would also introduce recursion into this, which we probably wanted to avoid due to performance issues.

Secondly, it probably makes all the SQL genreation cases more complex where this must be handled. I believe I decided the effort wasn't worth it, specifically because this more generic code would need be executed for every entity, probably slowing down the "regular identity cases".

**Comment by beberlei** [comment]
For example `$entityManager->find()` how would it work? would you *have* to pass an entity as the value? Because you'd otherwise need to say preresent the id as `['idAssoc' => ['id1' => 1, 'id2' => 2]]`.

**Comment by beberlei** [comment]
See this code here handling association ids, it assumes the identifier is single valued, otherwise there is a more complex pattern of code needed to make this work: https://github.com/doctrine/orm/blob/2.8.x/lib/Doctrine/ORM/UnitOfWork.php#L1141

This is probably just one of many instances where this would need to be handled.
