### ISSUE TITLE
1k issues! (some of them from 2013) is it doctrine ORM not ACTIVELY maintaining anymore? IS IT DEAD?

### ISSUE THREAD

**Issue by mdogancay** [doctrine/orm#8444]
Look at the ORM on github; whats going on? is this project dead? not actively maintaining by project owners anymore?

**Comment by Fedik** [comment]
No. Better look on the page with releases, than number of issues.

**Comment by mdogancay** [comment]
> No. Better look on the page with releases, than number of issues.

i already looked. total 19 issues solved in 2020. And there is 1k issues on tracker. I'm needing an answer from the project owners not from contributors.

**Comment by dbrumann** [comment]
@mdogancay This project is open source. Feel free to help out by confirming issues, providing test cases, fixing bugs. If you watch the repository you will see that there is quite some activity, but more people helping out will help reduce the backlog of existing issues.

**Comment by mdogancay** [comment]
> @mdogancay This project is open source. Feel free to help out by confirming issues, providing test cases, fixing bugs. If you watch the repository you will see that there is quite some activity, but more people helping out will help reduce the backlog of existing issues.

Thanks for the answer. The reason I'm asking this is because thousands of people are still actively using these projects. If the project is losing momentum (which it seems) we have to move towards an alternative choice. Developing a product with a dying project can result in serious financial losses! This is a serious situation. I trust the project managers to explain the situation when necessary.

**Comment by dbrumann** [comment]
> The reason I'm asking this is because thousands of people are still actively using these projects. If the project is losing momentum (which it seems) we have to move towards an alternative choice.

You don't necessarily have to move. You could also incentivise contributors and maintainers by supporting their efforts either financially or through active participation.

> Developing a product with a dying project can result in serious financial losses!

The fact that there was a release roughly a month ago (2020-12-04) should tell you that the project is not inactive. The work on an upcoming 2.9.x release could also help indicate at some activity. Not to mention the activity in sister projects like dbal and the releases there.

If you consider this project vital it might make sense to let the maintainers work on it instead of wasting their time with frivolous claims or requests of a risk assessment for your projects or whatever this is supposed to be.

If you have an alternative that you feel is more stable and a better choice for your project, feel free to switch to it. Otherwise I suggest you put your energy in supporting the dependencies that you feel are vital to your projects so they don't become "dying projects".

**Comment by greg0ire** [comment]
Let me close this as a way to show you that we do have a look at issues.

**Comment by mdogancay** [comment]
> Let me close this as a way to show you that we do have a look at issues.

@dbrumann , @greg0ire 
I am speaking the truth here, but you are making politics. Instead of looking for a solution to the problem, you're treating me badly and trying to silence me. I'm sorry, but I don't think you are "good people" anymore ... Yes, with your behavior, it became clear why this project is Dying ... Goodbye ...

**Comment by dbrumann** [comment]
I am sorry you think that way. I admit I was snarky, but if you read back your title and initial question, I hope you will realize that you are accusing a bunch of people who spend their free time on a project that you rely on on not doing enough - for you, for free. I think that is rude, which is why I reacted as I did.

As to your concerns, I think I have made it clear that your premise of not much activity doesn't hold up. Yes there are open issues and some of them old, but this is not uncommon and it's not the only activity metric (as shown in my previous comment). If you look at projects like symfony/symfony you will see they have quite a few open issues as well, some of them dating back to 2012, almost 10 years, but you could hardly call Symfony dead or inactive.

Again, if these open issues concern you, you should help out and look at them, help verify them maybe produce a test case and even fix them. This, in my opinion, is the only way to address the backlog constructively.

**Comment by beberlei** [comment]
@mdogancay Doctrine's code base is over 10 years old and heavily matured. While we do have 1000 open issues, when I worked through 100 of them in December only a small number was actually bugs, most of them are help requests and users wrongly using or misconfiguring. A lot of issues are feature requests that we tend to be conserative about and not consider.

The complexity of Doctrine often makes it very time consuming finding the ultimate problem of the user. We provide free software, not free support. 

Yes, not much is happening code wise, but that also means not a lot of stuff is breaking or requires your constant attention, getting to the new APIs.

There isn't an ORM in PHP that comes even close to features than Doctrine. Due to the nature of ORMs being leaky abstraction, it is my firm believe working on ORMs for 15 years now, that this feature richness comes at the price of complex and sometimes "fragile" internals (you can trade this off for better internals at low performance). As such you should be happy that we are keeping it working as is.

**Comment by greg0ire** [comment]
- [x] clickbaity title, with word in all caps
- [x] IS PROJECT DEAD
- [x] 0 contributions to the project ([1 attempt](https://github.com/doctrine/doctrine-website/pull/379), to be fair)
- [x] wants to talk to ~your manager~ the maintainers, not the contributors
- [x] maintainers are bad people

> Goodbye FOREVER...

![that was always allowed](https://comb.io/oCQ8gV.gif)

I don't know why people in this thread are dignifying OP's post with the lengthy and thoughtful answers. All this post deserves is to be ~silenced~ locked. OP can come back after calming down and finding the right tone to phrase his otherwise valid concerns. Because yes, tone matters.
