### ISSUE TITLE
AbstractCommand - assert accept only instanceof EntityManager

### ISSUE THREAD

**Issue by martinolmr** [doctrine/orm#8488]
**AbstractCommand, line 56**

Accept only EntityManager instances:

```php
assert($em instanceof EntityManager);
```

Should be:

```php
assert($em instanceof EntityManagerInterface);
```

**Comment by acelaya** [comment]
Same here. Looks like this happens since v2.8.2, as v2.8.1 doesn't throw `Fatal error: Uncaught AssertionError: assert($em instanceof EntityManager)`.

**Comment by greg0ire** [comment]
Out of curiosity, what is used there if not `EntityManager`? Some decorator?

**Comment by acelaya** [comment]
In my case yes, a decorator. It extends from this https://github.com/doctrine/orm/blob/2.8.x/lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php

**Comment by beberlei** [comment]
@acelaya what is the decorators purpose? Can you explain?

**Comment by acelaya** [comment]
Sure!

I serve my application with swoole. Since it keeps services in memory to reuse them on subsequetn requests, it can happen that the EntityManager has been closed for some reason, or the connection with the database has expired.

What my decorator does is allow to transparently recreate the wrapped EntityManager if needed.

To simplify things, I do this by exposing an `open` method which is called by a PSR-15 middleware, which also makes sure to close the DB connection and clear the EntityManager to avoid memory leaks or mixing units of work.

The project is open source, so you can see the code here:

* EntityManager decorator: https://github.com/shlinkio/shlink-common/blob/main/src/Doctrine/ReopeningEntityManager.php
* Middleware consuming it: https://github.com/shlinkio/shlink-common/blob/main/src/Middleware/CloseDbConnectionMiddleware.php
